apiVersion: batch/v1
kind: CronJob
metadata:
  name: re-evaluate-cronjob
  namespace: sysdig-agent
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: re-evaluate
            image: re-evaluate:0.1
            imagePullPolicy: Always
            env:
            - name: SECURE_API
              valueFrom:
                secretKeyRef:
                  name: re-evaluate-secrets
                  key: SECURE_API
            - name: SECURE_URL
              value: "app.us4.sysdig.com"
            - name: TIME_DIFF
              value: "86400"
          restartPolicy: OnFailure
