apiVersion: batch/v1
kind: CronJob
metadata:
  name: re-evaluate-cronjob
  namespace: sysdig-agent
spec:
  schedule: "20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: re-evaluate
            image: ghcr.io/kaz-sysdig/re-evaluate:0.3.5
            imagePullPolicy: Always
            env:
            - name: SECURE_API
              valueFrom:
                secretKeyRef:
                  name: re-evaluate-secrets
                  key: SECURE_API
            - name: SECURE_URL
              value: "kaztest0827.sysdiglabs.com"
            - name: TIME_DIFF
              value: "600"
          restartPolicy: OnFailure
